version: '3.9'

services:
  postgres:
    image: postgres:16.3
    container_name: postgres-container
    environment:
      POSTGRES_USER: sebastian
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: databaseHotel
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: